
CREATE TABLE USERS (id  INTEGER , name VARCHAR(250));
ALTER TABLE USERS MODIFY  id INT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE USERS ADD username VARCHAR(255);
ALTER TABLE USERS ADD password VARCHAR(255);
ALTER TABLE USERS ADD type int NULL;
ALTER TABLE USERS ADD holiday int NULL;
ALTER TABLE USERS ADD Confirmholiday int NULL;
INSERT INTO  USERS VALUES (2,'maram','maram','maram',NULL,NULL,NULL);
INSERT INTO  USERS VALUES (1,'lesly','lesly','lesly',1,NULL,NULL);